//created on: Oct 5, 2020
package EntenderParaMejorarRules

//list any import classes here.
import Models.HuellaCarbonoModel
import Enums.TipoAlimentacionEnum
import Enums.GestionResiduosEnum
import Enums.PlanHabitosMejorarEnum
import Enums.ImpactoIndividuoEmisorEnum


//declare any global variables here

rule "CantidadCO2Compost"
lock-on-active 
    when
        $huellaDeCarbono : HuellaCarbonoModel(indicadoresEmisionCO2Indirectos.gestionResiduos   == GestionResiduosEnum.Compost  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2GestionResiduos(0.8);
    	double indicadoresIndirectos = $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().getTotalCO2EmitidoIndirectamente();
        $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setTotalCO2EmitidoIndirectamente(indicadoresIndirectos + 0.8);
    	$huellaDeCarbono.setCantidadCO2Emitido(0.8 + $huellaDeCarbono.getCantidadCO2Emitido());
    	update($huellaDeCarbono);
end

rule "CantidadCO2SepararResiduos"
lock-on-active 
    when
        $huellaDeCarbono : HuellaCarbonoModel(indicadoresEmisionCO2Indirectos.gestionResiduos   == GestionResiduosEnum.SeparaResiduos  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2GestionResiduos(1.4);
    	double indicadoresIndirectos = $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().getTotalCO2EmitidoIndirectamente();
        $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setTotalCO2EmitidoIndirectamente(indicadoresIndirectos + 1.4);	
    	    	$huellaDeCarbono.setCantidadCO2Emitido(1.4 + $huellaDeCarbono.getCantidadCO2Emitido());
 
    	update($huellaDeCarbono);
end

rule "CantidadCO2NoHacerNada"
lock-on-active 
   when
        $huellaDeCarbono : HuellaCarbonoModel(indicadoresEmisionCO2Indirectos.gestionResiduos   == GestionResiduosEnum.NoHaceNada  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2GestionResiduos(0.8);
    	double indicadoresIndirectos = $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().getTotalCO2EmitidoIndirectamente();
        $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setTotalCO2EmitidoIndirectamente(indicadoresIndirectos + 0.8);
    	$huellaDeCarbono.setCantidadCO2Emitido(0.8 + $huellaDeCarbono.getCantidadCO2Emitido());
    	update($huellaDeCarbono);
end

rule "CantidadCO2AlimentacionVegana"
lock-on-active 
    when
        $huellaDeCarbono : HuellaCarbonoModel(indicadoresEmisionCO2Indirectos.tipoalimentacion   == TipoAlimentacionEnum.Vegana  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2TipoAlimentacion(1.13);
    	double indicadoresIndirectos = $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().getTotalCO2EmitidoIndirectamente();
        $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setTotalCO2EmitidoIndirectamente(indicadoresIndirectos + 1.13);
    	$huellaDeCarbono.setCantidadCO2Emitido(1.13 + $huellaDeCarbono.getCantidadCO2Emitido());

    	update($huellaDeCarbono);
end

rule "CantidadCO2AlimentacionVegetariana"
lock-on-active 
    when
        $huellaDeCarbono : HuellaCarbonoModel(indicadoresEmisionCO2Indirectos.tipoalimentacion   == TipoAlimentacionEnum.Vegetariana  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2TipoAlimentacion(1.58);
    	double indicadoresIndirectos = $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().getTotalCO2EmitidoIndirectamente();
        $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setTotalCO2EmitidoIndirectamente(indicadoresIndirectos + 1.58);
    	$huellaDeCarbono.setCantidadCO2Emitido(1.58 + $huellaDeCarbono.getCantidadCO2Emitido());
    	update($huellaDeCarbono);
end

rule "CantidadCO2AlimentacionPescetariana"
lock-on-active 
    when
        $huellaDeCarbono : HuellaCarbonoModel(indicadoresEmisionCO2Indirectos.tipoalimentacion   == TipoAlimentacionEnum.Pescetariana  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2TipoAlimentacion(1.66);
    	double indicadoresIndirectos = $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().getTotalCO2EmitidoIndirectamente();
        $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setTotalCO2EmitidoIndirectamente(indicadoresIndirectos + 1.66);
    	$huellaDeCarbono.setCantidadCO2Emitido(1.66 + $huellaDeCarbono.getCantidadCO2Emitido());
    	update($huellaDeCarbono);
end

rule "CantidadCO2AlimentacionOmnivora"
lock-on-active 
    when
        $huellaDeCarbono : HuellaCarbonoModel(indicadoresEmisionCO2Indirectos.tipoalimentacion   == TipoAlimentacionEnum.Omnivora  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2TipoAlimentacion(2.28);
    	double indicadoresIndirectos = $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().getTotalCO2EmitidoIndirectamente();
        $huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setTotalCO2EmitidoIndirectamente(indicadoresIndirectos + 2.28);
    	$huellaDeCarbono.setCantidadCO2Emitido(2.28 + $huellaDeCarbono.getCantidadCO2Emitido());
    	update($huellaDeCarbono);
end


rule "ImpactoBajo"
lock-on-active 
    when
        $huellaDeCarbono : HuellaCarbonoModel(cantidadCO2Emitido <10 )
    then  	
    	$huellaDeCarbono.getPlanReduccion().setImpactIndividuoEmisor(ImpactoIndividuoEmisorEnum.Bajo);
    	$huellaDeCarbono.getPlanReduccion().setPlanHabitosMejorar(PlanHabitosMejorarEnum.BajoImpacto);
       	update($huellaDeCarbono);
end


rule "ImpactoMedio"
lock-on-active 
    when
        $huellaDeCarbono : HuellaCarbonoModel(cantidadCO2Emitido >=10 && cantidadCO2Emitido < 20 )
    then
    	$huellaDeCarbono.getPlanReduccion().setImpactIndividuoEmisor(ImpactoIndividuoEmisorEnum.Medio);
    	$huellaDeCarbono.getPlanReduccion().setPlanHabitosMejorar(PlanHabitosMejorarEnum.MedioImpacto);
        update($huellaDeCarbono);
end

rule "ImpactoAlto"
lock-on-active 
    when
        $huellaDeCarbono : HuellaCarbonoModel(cantidadCO2Emitido >= 20 )
    then
    	$huellaDeCarbono.getPlanReduccion().setImpactIndividuoEmisor(ImpactoIndividuoEmisorEnum.Alto);
    	$huellaDeCarbono.getPlanReduccion().setPlanHabitosMejorar(PlanHabitosMejorarEnum.AltoImpacto);
        update($huellaDeCarbono);

end

rule "PlanBajoImpacto"
lock-on-active 
    when
        $huellaDeCarbono : HuellaCarbonoModel(planReduccion.impactIndividuoEmisor == ImpactoIndividuoEmisorEnum.Bajo  )
    then
    	$huellaDeCarbono.getPlanReduccion().setPlanHabitosMejorar(PlanHabitosMejorarEnum.BajoImpacto);
    	update($huellaDeCarbono);
end

rule "PlanMedioImpacto"
lock-on-active 
 when
        $huellaDeCarbono : HuellaCarbonoModel(planReduccion.impactIndividuoEmisor == ImpactoIndividuoEmisorEnum.Medio  )
    then
    	$huellaDeCarbono.getPlanReduccion().setPlanHabitosMejorar(PlanHabitosMejorarEnum.MedioImpacto);
    	update($huellaDeCarbono);
end

rule "PlanAltoImpacto"
lock-on-active 
     when
        $huellaDeCarbono : HuellaCarbonoModel(planReduccion.impactIndividuoEmisor == ImpactoIndividuoEmisorEnum.Alto  )
    then
    	$huellaDeCarbono.getPlanReduccion().setPlanHabitosMejorar(PlanHabitosMejorarEnum.AltoImpacto);
    	update($huellaDeCarbono);
end
 