//created on: Oct 5, 2020
package EntenderParaMejorarRules

//list any import classes here.
import Models.HuellaCarbonoModel
import Models.PlanReduccionModel
import Models.IndicadoresEmisionCO2IndirectosModel
import Models.IndicadoresEmisionCO2DirectosModel
import AggregatesModels.MedioTransporteCotidiano
import AggregatesModels.MedioTransporteLargaDistancia
import AggregatesModels.ConstanteMultiplicativaTransporteLargaDistancia
import AggregatesModels.ConstanteMultiplicativaTransporteCotidiano
import AggregatesModels.RecorridoTransporteCotidiano
import AggregatesModels.RecorridoTransporteLargaDistancia
import Enums.TipoAlimentacionEnum
import Enums.GestionResiduosEnum
import Enums.PlanHabitosMejorarEnum
import Enums.ImpactoIndividuoEmisorEnum


//declare any global variables here




rule "ImpactoBajo"

    when
        $huellaCarbono : HuellaCarbonoModel( cantidadCO2Emitido <10 )
    then
    	PlanReduccionModel test = new PlanReduccionModel();
    	test.setImpactIndividuoEmisor(ImpactoIndividuoEmisorEnum.Bajo);
        $huellaCarbono.setPlanReduccion(test);
       	update($huellaCarbono);
    	System.out.println("Entre");
end


rule "ImpactoMedio"

    when
        $huellaCarbono : HuellaCarbonoModel( cantidadCO2Emitido >=10 && cantidadCO2Emitido < 20 )
    then
    	PlanReduccionModel planReduccion = $huellaCarbono.getPlanReduccion();
    	planReduccion.setImpactIndividuoEmisor(ImpactoIndividuoEmisorEnum.Medio);
        $huellaCarbono.setPlanReduccion(planReduccion);
        update($huellaCarbono);
    	System.out.println("Entre");
end

rule "ImpactoAlto"

    when
        $huellaCarbono : HuellaCarbonoModel( cantidadCO2Emitido >= 20 )
    then
    	PlanReduccionModel planReduccion = $huellaCarbono.getPlanReduccion();
    	planReduccion.setImpactIndividuoEmisor(ImpactoIndividuoEmisorEnum.Alto);
        $huellaCarbono.setPlanReduccion(planReduccion);
        update($huellaCarbono);
    	System.out.println("Entre");

end

rule "PlanBajoImpacto"

    when
        $huellaDeCarbono : HuellaCarbonoModel( planReduccion.impactIndividuoEmisor == ImpactoIndividuoEmisorEnum.Bajo  )
    then
    	$huellaDeCarbono.getPlanReduccion().setPlanHabitosMejorar(PlanHabitosMejorarEnum.BajoImpacto);
    	update($huellaDeCarbono);
    	System.out.println("Entre");
end

rule "PlanMedioImpacto"

 when
        $huellaDeCarbono : HuellaCarbonoModel( planReduccion.impactIndividuoEmisor == ImpactoIndividuoEmisorEnum.Medio  )
    then
    	$huellaDeCarbono.getPlanReduccion().setPlanHabitosMejorar(PlanHabitosMejorarEnum.MedioImpacto);
    	update($huellaDeCarbono);
    	System.out.println("Entre");
end

rule "PlanAltoImpacto"

     when
        $huellaDeCarbono : HuellaCarbonoModel( planReduccion.impactIndividuoEmisor == ImpactoIndividuoEmisorEnum.Alto  )
    then
    	$huellaDeCarbono.getPlanReduccion().setPlanHabitosMejorar(PlanHabitosMejorarEnum.AltoImpacto);
    	update($huellaDeCarbono);
    	System.out.println("Entre");
end
 
rule "CantidadCO2Compost"

    when
        $huellaDeCarbono : HuellaCarbonoModel( indicadoresEmisionCO2Indirectos.getionResiduos  == GestionResiduosEnum.Compost  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2GestionResiduos(0.8);
    	update($huellaDeCarbono);
    	System.out.println("Entre");
end

rule "CantidadCO2SepararResiduos"

    when
        $huellaDeCarbono : HuellaCarbonoModel( indicadoresEmisionCO2Indirectos.getionResiduos  == GestionResiduosEnum.SeparaResiduos  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2GestionResiduos(1.4);
    	update($huellaDeCarbono);
    	System.out.println("Entre");
end

rule "CantidadCO2NoHacerNada"

    when
        $huellaDeCarbono : HuellaCarbonoModel( indicadoresEmisionCO2Indirectos.getionResiduos  == GestionResiduosEnum.NoHacerNada  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2GestionResiduos(2.1);
    	update($huellaDeCarbono);
    	System.out.println("Entre");
end

rule "CantidadCO2AlimentacionVegana"

    when
        $huellaDeCarbono : HuellaCarbonoModel( indicadoresEmisionCO2Indirectos.tipoalimentacion   == TipoAlimentacionEnum.Vegana  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2TipoAlimentacion(1.13);
    	update($huellaDeCarbono);
    	System.out.println("Entre");
end

rule "CantidadCO2AlimentacionVegetariana"

    when
        $huellaDeCarbono : HuellaCarbonoModel( indicadoresEmisionCO2Indirectos.tipoalimentacion   == TipoAlimentacionEnum.Vegetariana  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2TipoAlimentacion(1.58);
    	update($huellaDeCarbono);
    	System.out.println("Entre");
end

rule "CantidadCO2AlimentacionPescetariana"

    when
        $huellaDeCarbono : HuellaCarbonoModel( indicadoresEmisionCO2Indirectos.tipoalimentacion   == TipoAlimentacionEnum.Pescetariana  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2TipoAlimentacion(1.66);
    	update($huellaDeCarbono);
    	System.out.println("Entre");
end

rule "CantidadCO2AlimentacionOmnivora"

    when
        $huellaDeCarbono : HuellaCarbonoModel( indicadoresEmisionCO2Indirectos.tipoalimentacion   == TipoAlimentacionEnum.Omnivora  )
    then
    	$huellaDeCarbono.getIndicadoresEmisionCO2Indirectos().setCantidadCO2TipoAlimentacion(2.28);
    	update($huellaDeCarbono);
    	System.out.println("Entre");
end